# Generated by Django 5.0.4 on 2024-04-30 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicantsReg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicants_guardian_details',
            old_name='next_of_kin_relatioship',
            new_name='next_of_kin_relationship',
        ),
    ]
