# Generated by Django 5.0.4 on 2024-05-01 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicantsReg', '0003_alter_addmitted_student_addmission_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicant_selections',
            options={'verbose_name_plural': 'Applicant Selections'},
        ),
        migrations.AlterModelOptions(
            name='applicants_academic_qualification',
            options={'verbose_name_plural': 'Academic Qualifications'},
        ),
        migrations.AlterField(
            model_name='addmitted_student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='addmitted_student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='applicant_other_qualifications',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='other_qualifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='applicant_personal_details',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='applicant_selections',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='applicants_academic_qualification',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic_qualifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='applicants_guardian_details',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_details', to=settings.AUTH_USER_MODEL),
        ),
    ]
