# Generated by Django 5.0.4 on 2024-05-02 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicantsReg', '0004_alter_applicant_selections_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant_other_qualifications',
            name='training_or_workshop1',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='applicant_other_qualifications',
            name='training_or_workshop2',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='applicant_other_qualifications',
            name='training_or_workshop3',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
