# Generated by Django 5.0.4 on 2024-05-04 22:11

import applicantsReg.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicantsReg', '0006_alter_applicants_guardian_details_next_of_kin_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmitted_student',
            name='submission_time',
            field=applicantsReg.models.SubmissionTimeField(null=True),
        ),
        migrations.AddField(
            model_name='applicant_other_qualifications',
            name='submission_time',
            field=applicantsReg.models.SubmissionTimeField(null=True),
        ),
        migrations.AddField(
            model_name='applicant_personal_details',
            name='submission_time',
            field=applicantsReg.models.SubmissionTimeField(null=True),
        ),
        migrations.AddField(
            model_name='applicant_selections',
            name='submission_time',
            field=applicantsReg.models.SubmissionTimeField(null=True),
        ),
        migrations.AddField(
            model_name='applicants_academic_qualification',
            name='submission_time',
            field=applicantsReg.models.SubmissionTimeField(null=True),
        ),
        migrations.AddField(
            model_name='applicants_guardian_details',
            name='submission_time',
            field=applicantsReg.models.SubmissionTimeField(null=True),
        ),
    ]
