# Generated by Django 5.0.4 on 2024-05-07 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicantsReg', '0008_addmitted_student_addmission_approval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmitted_student',
            name='addmission_leter',
            field=models.FileField(null=True, upload_to='addmission_letter/'),
        ),
    ]
