# Generated by Django 5.0.4 on 2024-05-08 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicantsReg', '0009_addmitted_student_addmission_leter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='reffered_by',
        ),
        migrations.AddField(
            model_name='customuser',
            name='referred_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL),
        ),
    ]
