# Generated by Django 5.0.4 on 2024-05-09 22:51

import applicantsReg.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicantsReg', '0010_remove_customuser_reffered_by_customuser_referred_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmitted_student',
            name='Other_payment_reciept',
            field=applicantsReg.models.LimitedFileField(upload_to='payment_reciepts/fees/', validators=[applicantsReg.models.validate_file_extension, applicantsReg.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='addmitted_student',
            name='addmission_leter',
            field=applicantsReg.models.LimitedFileField(null=True, upload_to='addmission_letter/', validators=[applicantsReg.models.validate_file_extension, applicantsReg.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='addmitted_student',
            name='hostel_fees_payment_reciept',
            field=applicantsReg.models.LimitedFileField(upload_to='payment_reciepts/fees/', validators=[applicantsReg.models.validate_file_extension, applicantsReg.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='addmitted_student',
            name='tuition_fees_payment_reciept',
            field=applicantsReg.models.LimitedFileField(upload_to='payment_reciepts/fees/', validators=[applicantsReg.models.validate_file_extension, applicantsReg.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='applicant_other_qualifications',
            name='CV_document',
            field=applicantsReg.models.LimitedFileField(blank=True, null=True, upload_to='transcripts/', validators=[applicantsReg.models.validate_file_extension, applicantsReg.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='applicant_other_qualifications',
            name='other_attachments1',
            field=applicantsReg.models.LimitedFileField(blank=True, null=True, upload_to='otherAttachments/', validators=[applicantsReg.models.validate_file_extension, applicantsReg.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='applicant_other_qualifications',
            name='other_attachments2',
            field=applicantsReg.models.LimitedFileField(blank=True, null=True, upload_to='otherAttachments/', validators=[applicantsReg.models.validate_file_extension, applicantsReg.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='applicant_other_qualifications',
            name='other_attachments3',
            field=applicantsReg.models.LimitedFileField(blank=True, null=True, upload_to='otherAttachments/', validators=[applicantsReg.models.validate_file_extension, applicantsReg.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='applicant_other_qualifications',
            name='training_and_workshops',
            field=applicantsReg.models.LimitedFileField(blank=True, null=True, upload_to='otherAttachments/', validators=[applicantsReg.models.validate_file_extension, applicantsReg.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='applicants_academic_qualification',
            name='certificate_file',
            field=applicantsReg.models.LimitedFileField(upload_to='certificates/', validators=[applicantsReg.models.validate_file_extension, applicantsReg.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='applicants_academic_qualification',
            name='results_transcripts',
            field=applicantsReg.models.LimitedFileField(blank=True, null=True, upload_to='transcripts/', validators=[applicantsReg.models.validate_file_extension, applicantsReg.models.validate_file_extension]),
        ),
    ]
